chore: maybe auto

diff --git a/scripts/nix-update b/scripts/nix-update
--- a/scripts/nix-update
+++ b/scripts/nix-update
@@ -5,6 +5,36 @@ shopt -s inherit_errexit 2>/dev/null || :
 
 cd "$(dirname "$0")"/..
 
+# check sources for updates with nvfetcher
 nvfetcher -k ~/.config/nvfetcher/keyfile.toml -o overlays/.nvfetcher
 
+# fixup some nvfetcher sources with dependencies
+(
+	# get the current flake's store path
+	NIX_PATH="nixpkgs=$(nix flake prefetch nixpkgs --json | jq --raw-output '.storePath')"
+	export NIX_PATH
+	echo "$NIX_PATH"
+
+	# used to collect command output while still piping it to stdout
+	exec 5>&1
+
+	# oh-my-posh
+	oh_my_posh="$(
+		cat <<EOF
+{ pkgs ? import <nixpkgs> { overlays = [(import ./overlays/oh-my-posh-overlay.nix {}) ]; } }:
+pkgs.oh-my-posh
+EOF
+	)"
+
+	# this command succeeds if its already in the store,
+	# otherwise it tries to build, captures the correct hash, and updates generated.json
+	if output=$(nix-build --expr "$oh_my_posh" 2>&1 | tee >(cat - >&5) || true); then
+		# if the command fails, it should just be on the vendor hash which is captured
+		vendor_hash=$(echo "$output" | grep -oP 'got:\s+\Ksha256-[a-zA-Z0-9+/=]+')
+		echo -e "\nUpdating vendorHash: $vendor_hash\n"
+		yq e -iP '.oh-my-posh.vendorHash = "'"$vendor_hash"'"' overlays/.nvfetcher/generated.json -o json
+	fi
+)
+
+# update flake dependencies
 nix flake update
